### PR TITLE
Fixed a bug, where libs with dasherized names could not be used corre…

### PR DESCRIPTION
**Pull request by johannwagner**
…ctly.

Fixed Issue #7.

### CODE REVIEW

**Comment by johannwagner** [comment]
@bengsparks

**Review by fin-ger — COMMENTED** [review]
It is actually quite common for go libraries to contain dashes in their name (e.g. https://github.com/op/go-logging). However the package name itself does not contain dashes. I am not sure how to handle this properly in burrow. Maybe we should replace dashes with underscores in the package name and leave the dashes in the project name (folder name, etc.). Please add your comments!

**Comment by martin31821** [comment]
@fin-ger 
1. Nothing stops you from using a git remote with dashes (just like go logging does)
2. It is good convention to keep package names short and readable, as per https://blog.golang.org/package-names
3. Underscores are not allowed, either afaik

**Comment by fin-ger** [comment]
The location of the burrow package in the go path prevents me from using a git remote other than the one created with `burrow new`. When the git remote differs from the location burrow uses when creating the project, import paths get messed up.

Underscores are possible in package names but not idiomatic. Thats why I have not fixed the issue yet.

Does anyone have an idea how to handle this while still using idiomatic go package names?

**Comment by fin-ger** [comment]
We could add a question to the project setup that asks for the package name which defaults to the project name. When the package name contains an invalid character the input will not be accepted (possibly telling the user which character is invalid). This would allow the user to specify another name for the package than for the project.

**Comment by fin-ger** [comment]
EOL

**Pull request closed without merging**
