### PR TITLE
Fix/vet crosscompile

### PR DESCRIPTION
**Pull request by martin31821**
Use `go vet` instead of go tool vet. 

To have this work, I added a piece of code which performs an `os.Chdir` on the burrow process to be executed within the `GOPATH`.

This fixes import errors when checking code while cross-compiling.

### CODE REVIEW

**Comment by martin31821** [comment]
For reference (and this is, I think, also the root cause of the original bug) this is the code which backs `os.Getwd()`: [getwd.go](https://golang.org/src/os/getwd.go). On linux, it consults the `PWD` environment variable, which is the working directory when **entering** the process, but when the process changes its directory via syscall `chdir`, `PWD` remains unchanged to keep the information.

The problem is, that go checks whether the `PWD` and the directory changed to refer to the same file, which is the case when we `chdir` from a symlink to the backing directory.

**Comment by fin-ger** [comment]
Why is this necessary? `ExecDir` should do the job. We should not need to change the working directory for the burrow root process. It should be enough to only run subprocesses in another directory.

Also have you checked, that this does not introduce any regression bugs? It looks really risky to change the root environment when other actions are _expecting_ burrow to run in the environment the user started the application.

**Comment by martin31821** [comment]
This is necessary, since `ExecDir` won't change `PWD` and therefore the path reported by `os.Getwd` (which is what `go` is internally using) returns the wrong (symlinked) path instead of the absolute path, even though the working directory is correct.

I also tried setting `PWD` myself for the child process, but that lead to strange behavior within the `go` tool, I don't want to say it's impossible, but I couldn't figure it out.

Moreover, all other tools remain untouched, since we are not actually **changing** the working directory, but just resolving the symlink, so relative file URLs etc. stay the same.

**Comment by fin-ger** [comment]
So as `ExecDir` is not working as expected, I would suggest to remove this function with this PR.

**Comment by martin31821** [comment]
We can't remote `ExecDir` since it's required for `burrow init/create` and works as expected there (since there are no symlinks involved)

**Comment by martin31821** [comment]
As I discovered today, this is a BREAKING change, before `go vet` warnings were not treated as errors so programs could have go vet errors but compile fine with burrow.

**Review by fin-ger — APPROVED** [review]
Looks good to me

**Pull request merged**
